//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraExcepcion
    {
        public int IdBitacoraExepcion { get; set; }
        public string Aplicacion { get; set; }
        public string Modulo { get; set; }
        public string Funcion { get; set; }
        public string DescExcepcion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string UsuarioRegistro { get; set; }
    }
}
