//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraSistema
    {
        public int IdBitacora { get; set; }
        public string BitacoraTabla { get; set; }
        public string BitacoraIdReg { get; set; }
        public string BitacoraCampo { get; set; }
        public string BitacoraValorAnt { get; set; }
        public string BitacoraObservaciones { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
