//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_TipoPersonaReferencia
    {
        public Cat_TipoPersonaReferencia()
        {
            this.PersonaReferencia = new HashSet<PersonaReferencia>();
        }
    
        public byte IdTipoPersonaRef { get; set; }
        public string DescripcionTipoPersona { get; set; }
        public string Observaciones { get; set; }
        public bool EstatusRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
    
        public virtual ICollection<PersonaReferencia> PersonaReferencia { get; set; }
    }
}
