//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_InstitucionContratosDBCATNueva
    {
        public int ClaveInstitucion { get; set; }
        public string NombreInstitucion { get; set; }
        public string DescripcionInstitucionDBCAT { get; set; }
        public Nullable<int> IdInstitucionDBCAT { get; set; }
    }
}
