//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Prioridad
    {
        public Cat_Prioridad()
        {
            this.AreaPrioridad = new HashSet<AreaPrioridad>();
        }
    
        public int IdPrioridad { get; set; }
        public string DescripcionPrioridad { get; set; }
        public bool EstatusRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual ICollection<AreaPrioridad> AreaPrioridad { get; set; }
    }
}
