//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_CampoReporte
    {
        public int IdCampoReporte { get; set; }
        public int Fk_IdReporte { get; set; }
        public int OrdenCampoReporte { get; set; }
        public string NombreCampoReporte { get; set; }
        public string DescripcionCampoReporte { get; set; }
        public bool EstatusRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
