//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptoAccesibilidad
    {
        public ConceptoAccesibilidad()
        {
            this.Movimiento = new HashSet<Movimiento>();
        }
    
        public int IdConcAccesibilidad { get; set; }
        public Nullable<int> Fk_IdIndicador { get; set; }
        public Nullable<int> Fk_IdAreaPrioridad { get; set; }
        public string DescConcAccesibilidad { get; set; }
        public Nullable<int> Cumplimiento { get; set; }
        public int EstatusRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual AreaPrioridad AreaPrioridad { get; set; }
        public virtual Cat_Indicador Cat_Indicador { get; set; }
        public virtual ICollection<Movimiento> Movimiento { get; set; }
    }
}
