//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratosArrtoRIUF
    {
        public int NoContrato { get; set; }
        public string Estado { get; set; }
        public string Municipio { get; set; }
        public string RIUF { get; set; }
        public string Promovente { get; set; }
        public string Secuencial { get; set; }
        public string Propietario { get; set; }
        public Nullable<System.DateTime> FechaDictamen { get; set; }
        public string Responsable { get; set; }
        public string Sector { get; set; }
        public string Ciudad { get; set; }
        public string Colonia { get; set; }
        public string Calle { get; set; }
        public string CP { get; set; }
        public string NumInt { get; set; }
        public string NumExt { get; set; }
        public Nullable<double> MontoDictaminado { get; set; }
        public Nullable<System.DateTime> FechaInicioContrato { get; set; }
        public Nullable<System.DateTime> FechaFinContrato { get; set; }
        public Nullable<double> CajonesEstacionamiento { get; set; }
        public string TipoContratacion { get; set; }
        public Nullable<double> RentaMensualUnitaria { get; set; }
        public Nullable<double> MontoRentaMensualAPagar { get; set; }
        public Nullable<double> AreaRentable { get; set; }
        public string UsoInmuble { get; set; }
        public string OtroUsoInmueble { get; set; }
        public Nullable<double> TablaSMOI { get; set; }
        public Nullable<double> CuotaMantenimiento { get; set; }
        public Nullable<double> MontoAnterior { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
