//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoArrto
    {
        public ContratoArrto()
        {
            this.ContratoArrto1 = new HashSet<ContratoArrto>();
            this.ExcepcionNormativaContratoArrto = new HashSet<ExcepcionNormativaContratoArrto>();
            this.PersonaReferencia = new HashSet<PersonaReferencia>();
            this.JustipreciacionArrto = new HashSet<JustipreciacionArrto>();
            this.Convenio_Modificatorio = new HashSet<Convenio_Modificatorio>();
        }
    
        public int IdContratoArrto { get; set; }
        public int FolioContratoArrto { get; set; }
        public byte Fk_IdTipoContrato { get; set; }
        public byte Fk_IdTipoArrendamiento { get; set; }
        public Nullable<byte> Fk_IdTipoContratacion { get; set; }
        public int Fk_IdInmuebleArrendamiento { get; set; }
        public Nullable<int> Fk_NumContratoHistorico { get; set; }
        public Nullable<int> Fk_IdContratoArrtoPadre { get; set; }
        public Nullable<int> Fk_IdTipoUsoInm { get; set; }
        public string OtroUsoInmueble { get; set; }
        public Nullable<int> Fk_IdTipoOcupacion { get; set; }
        public string OtroTipoOcupacion { get; set; }
        public int Fk_IdTipoMoneda { get; set; }
        public int Fk_IdInstitucion { get; set; }
        public string NombreInstitucion { get; set; }
        public System.DateTime FechaInicioOcupacion { get; set; }
        public System.DateTime FechaFinOcupacion { get; set; }
        public decimal AreaOcupadaM2 { get; set; }
        public decimal MontoPagoMensual { get; set; }
        public decimal MontoPagoPorCajonesEstacionamiento { get; set; }
        public decimal CuotaMantenimiento { get; set; }
        public decimal PtjeImpuesto { get; set; }
        public Nullable<int> Fk_IdAplicacionConcepto { get; set; }
        public string NumeroDictamenExcepcionFolioSMOI { get; set; }
        public string RIUF { get; set; }
        public string PropietarioInmueble { get; set; }
        public string FuncionarioResponsable { get; set; }
        public string Observaciones { get; set; }
        public bool EstatusRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public string CargoUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<bool> EsPadre { get; set; }
        public bool EsRUSP { get; set; }
        public Nullable<bool> CuentaConDictamen { get; set; }
        public Nullable<System.DateTime> FechaDictamen { get; set; }
    
        public virtual AplicacionConcepto AplicacionConcepto { get; set; }
        public virtual Cat_TipoArrendamiento Cat_TipoArrendamiento { get; set; }
        public virtual Cat_TipoContratacion Cat_TipoContratacion { get; set; }
        public virtual Cat_TipoContrato Cat_TipoContrato { get; set; }
        public virtual Cat_TipoOcupacion Cat_TipoOcupacion { get; set; }
        public virtual ICollection<ContratoArrto> ContratoArrto1 { get; set; }
        public virtual ContratoArrto ContratoArrto2 { get; set; }
        public virtual ContratoArrto_Historico ContratoArrto_Historico { get; set; }
        public virtual InmuebleArrendamiento InmuebleArrendamiento { get; set; }
        public virtual ICollection<ExcepcionNormativaContratoArrto> ExcepcionNormativaContratoArrto { get; set; }
        public virtual ICollection<PersonaReferencia> PersonaReferencia { get; set; }
        public virtual ICollection<JustipreciacionArrto> JustipreciacionArrto { get; set; }
        public virtual ICollection<Convenio_Modificatorio> Convenio_Modificatorio { get; set; }
    }
}
