//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratosVigentes
    {
        public int ID { get; set; }
        public string Secuencial { get; set; }
        public Nullable<int> FolioContrato { get; set; }
        public Nullable<int> FolioContratoAnterior { get; set; }
        public string Propietario { get; set; }
        public string Responsable { get; set; }
        public string Promovente { get; set; }
        public string Pais { get; set; }
        public string Estado { get; set; }
        public string Municipio { get; set; }
        public string Colonia { get; set; }
        public string Calle { get; set; }
        public string CodigoPostal { get; set; }
        public string NumInterior { get; set; }
        public string NumExterior { get; set; }
        public string Ciudad { get; set; }
        public string OtroUsoInmueble { get; set; }
        public string TipoContrato { get; set; }
        public string TipoOcupacion { get; set; }
        public string DescripcionTipoArrendamiento { get; set; }
        public string TipoInmueble { get; set; }
        public string TipoUsoInmueble { get; set; }
        public Nullable<double> AreaOcupadaM2 { get; set; }
        public Nullable<double> MontoPagoMensual { get; set; }
        public Nullable<double> CuotaMantenimiento { get; set; }
        public Nullable<double> MontoPagoPorCajonesEstacionamiento { get; set; }
        public Nullable<double> MontoDictaminado { get; set; }
        public Nullable<double> RentaUnitariaMensual { get; set; }
        public Nullable<double> MontoAnterior { get; set; }
        public Nullable<double> SMOI { get; set; }
        public string TablaSmoi { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaContratoDesde { get; set; }
        public Nullable<System.DateTime> FechaContratoHasta { get; set; }
        public Nullable<System.DateTime> FechaDictamen { get; set; }
        public string DescripcionTipoContratacion { get; set; }
        public string ResultadoOpinion { get; set; }
        public string RIUF { get; set; }
    }
}
