//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcepcionNormativaContratoArrto
    {
        public int IdContratoArrto { get; set; }
        public byte IdTipoExcepcionNormativaContrato { get; set; }
        public string Observaciones { get; set; }
        public bool EstatusRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Cat_TipoExcepcionNormativaContrato Cat_TipoExcepcionNormativaContrato { get; set; }
        public virtual ContratoArrto ContratoArrto { get; set; }
    }
}
