//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class JustipreciacionExt
    {
        public int IdJustipreciacionExt { get; set; }
        public string Secuencial { get; set; }
        public string NoGenerico { get; set; }
        public System.DateTime FechaDictamen { get; set; }
        public string UnidadResponsable { get; set; }
        public decimal TerrenoDictaminado { get; set; }
        public short Fk_IdUnidadMedidaTerrenoDict { get; set; }
        public decimal RentableDictamindo { get; set; }
        public short Fk_IdUnidadMedidaRentableDict { get; set; }
        public decimal ConstruidaDictaminado { get; set; }
        public short Fk_IdUnidadMedidaConstruidaDict { get; set; }
        public decimal MontoDictaminado { get; set; }
        public short Fk_IdSector { get; set; }
        public short Fk_IdInstitucion { get; set; }
        public string Colonia { get; set; }
        public string Calle { get; set; }
        public string NumExterior { get; set; }
        public string NumInterior { get; set; }
        public string CodigoPostal { get; set; }
        public short Fk_IdEstado { get; set; }
        public short Fk_IdMunicipio { get; set; }
        public string RutaDocumento { get; set; }
        public bool EstatusRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
