//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaReferencia
    {
        public int IdPersonaReferencia { get; set; }
        public int Fk_IdContratoArrto { get; set; }
        public byte Fk_IdTipoPersonaRef { get; set; }
        public string NombreCargo { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Email { get; set; }
        public bool EstatusRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Cat_TipoPersonaReferencia Cat_TipoPersonaReferencia { get; set; }
        public virtual ContratoArrto ContratoArrto { get; set; }
    }
}
