//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlazasInmueble
    {
        public int IdPlazaInm { get; set; }
        public string RFI { get; set; }
        public int Ramo { get; set; }
        public string UR { get; set; }
        public Nullable<int> NumPlazas { get; set; }
        public Nullable<bool> Operacion { get; set; }
        public int TotalPlazas { get; set; }
        public decimal SupConstM2 { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public bool Existe { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> EstatusRegistro { get; set; }
    }
}
