//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteTotal
    {
        public int NumeroSecuencial { get; set; }
        public int Id { get; set; }
        public int Fk_IdInstitucion { get; set; }
        public int No { get; set; }
        public int FolioContrato { get; set; }
        public Nullable<int> FolioContratoAnterior { get; set; }
        public string TipoContrato { get; set; }
        public string TipoOcupacion { get; set; }
        public string Secuencial { get; set; }
        public string Propietario { get; set; }
        public Nullable<System.DateTime> FechaDictamen { get; set; }
        public string Responsable { get; set; }
        public string Sector { get; set; }
        public string Promovente { get; set; }
        public int FkIdPais { get; set; }
        public int Pais { get; set; }
        public Nullable<int> Fk_IdEstado { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Fk_IdMunicipio { get; set; }
        public string Municipio { get; set; }
        public Nullable<int> Fk_IdLocalidad { get; set; }
        public short RetrieveBusColonia { get; set; }
        public string Colonia { get; set; }
        public string Calle { get; set; }
        public string CodigoPostal { get; set; }
        public string NumInterior { get; set; }
        public string NumExterior { get; set; }
        public string Ciudad { get; set; }
        public decimal MontoDictaminado { get; set; }
        public System.DateTime FechaContratoDesde { get; set; }
        public System.DateTime FechaCntratoHasta { get; set; }
        public short Fk_IdTipoArrendamiento { get; set; }
        public string DescripcionTipoArrendamiento { get; set; }
        public short Fk_IdTipoInmueble { get; set; }
        public string TipoInmueble { get; set; }
        public decimal MontoPagoPorCajonesEstacionamiento { get; set; }
        public Nullable<int> Fk_IdTipoContratacion { get; set; }
        public string DescripcionTipoContratacion { get; set; }
        public Nullable<decimal> RentaUnitariaMensual { get; set; }
        public Nullable<decimal> MontoPagoMensual { get; set; }
        public Nullable<decimal> CuotaMantenimiento { get; set; }
        public Nullable<double> AreaOcupadaM2 { get; set; }
        public int Fk_IdTipoUsoInmueble { get; set; }
        public string TipoUsoInmueble { get; set; }
        public string OtroUsoInmueble { get; set; }
        public string TablaSMOI { get; set; }
        public string ResultadosOpinion { get; set; }
        public decimal MontoAnterior { get; set; }
        public double SMOI { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string RIUF { get; set; }
        public Nullable<decimal> GeoRefLatitud { get; set; }
        public Nullable<decimal> GeoRefLongitud { get; set; }
    }
}
