//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelloDigital
    {
        public short Fk_IdCatTabla { get; set; }
        public int Fk_IdRegistroTablaOrigen { get; set; }
        public string CadenaOriginal { get; set; }
        public string SelloDigital1 { get; set; }
        public string GUID { get; set; }
        public bool EstatusRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public string QR { get; set; }
    
        public virtual Cat_Tabla Cat_Tabla { get; set; }
    }
}
