//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRADUCTOR_cat
    {
        public int Fk_IdInstitucion { get; set; }
        public string nombreInstitucionOrg { get; set; }
        public string nombreInstitucion { get; set; }
        public int Fk_IdInstitucionDB { get; set; }
        public string nombreInstitucionDB { get; set; }
    }
}
