//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraductorRUSP_INST
    {
        public Nullable<double> CveInst { get; set; }
        public string NombreInst { get; set; }
        public Nullable<double> CveSector { get; set; }
        public string NomSector { get; set; }
        public Nullable<double> CveNatJuridica { get; set; }
        public string NatJuridica { get; set; }
        public Nullable<bool> flag { get; set; }
        public bool estatus { get; set; }
        public Nullable<double> Ramo { get; set; }
        public string UR { get; set; }
        public string UnidadResponsableSHCP { get; set; }
    }
}
