//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DWH_RIUF
    {
        public int idRIUF { get; set; }
        public Nullable<int> IdEstadoRIUF { get; set; }
        public int Consecutivo { get; set; }
        public int DigitoVerificador { get; set; }
        public string Pais { get; set; }
        public string EntidadFederativa { get; set; }
        public string Municipio { get; set; }
        public string Colonia { get; set; }
        public string OtraColonia { get; set; }
        public string TipoVialidad { get; set; }
        public string NombreVialidad { get; set; }
        public string NumExterior { get; set; }
        public string NumInterior { get; set; }
        public string CodigoPostal { get; set; }
    }
}
